export const LIB_NAME = "DefendJS";
export const LIB_VERSION = "1.0.0";

export const ADAPTERS = {
    HASHING_PRIMARY: "HASHING_PRIMARY",
    HASHING_FALLBACK: "HASHING_FALLBACK",
    RATE_LIMITER: "RATE_LIMITER",
    VALIDATOR: "VALIDATOR",
    SANITIZER: "SANITIZER",
    COMPRESSION: "COMPRESSION",
    CSRF: "CSRF"
} as const;

export const MANAGERS = {
    HASH_MANAGER: "HASH_MANAGER",
    RATE_LIMIT_MANAGER: "RATE_LIMIT_MANAGER",
    VALIDATION_MANAGER: "VALIDATION_MANAGER",
    SANITIZER_MANAGER: "SANITIZER_MANAGER",
    CORS_MANAGER: "CORS_MANAGER",
    JSON_MANAGER: "JSON_MANAGER",
    AUTH_MANAGER: "AUTH_MANAGER",
    COMPRESSION_MANAGER: "COMPRESSION_MANAGER",
    CSRF_MANAGER: "CSRF_MANAGER",
    REQUEST_ID_MANAGER: "REQUEST_ID_MANAGER"
} as const;

export const ERROR_CODES = {
    ADAPTER_FAILURE: "ADAPTER_FAILURE",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    SANITIZER_ERROR: "SANITIZER_ERROR",
    AUTH_ERROR: "AUTH_ERROR",
    CONFIG_ERROR: "CONFIG_ERROR",
    SECURITY_ERROR: "SECURITY_ERROR",
    UNKNOWN: "UNKNOWN"
} as const;

export const PRESETS = {
    API: 'api',
    STRICT: 'strict',
    PUBLIC: 'public',
    DEFAULT: 'default'
} as const;